/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TractosRouteImport } from './routes/tractos'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as RemolquesRouteImport } from './routes/remolques'
import { Route as ProductividadRouteImport } from './routes/productividad'
import { Route as DhoRouteImport } from './routes/dho'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as IndexRouteImport } from './routes/index'

const TractosRoute = TractosRouteImport.update({
  id: '/tractos',
  path: '/tractos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const RemolquesRoute = RemolquesRouteImport.update({
  id: '/remolques',
  path: '/remolques',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductividadRoute = ProductividadRouteImport.update({
  id: '/productividad',
  path: '/productividad',
  getParentRoute: () => rootRouteImport,
} as any)
const DhoRoute = DhoRouteImport.update({
  id: '/dho',
  path: '/dho',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dho': typeof DhoRoute
  '/productividad': typeof ProductividadRoute
  '/remolques': typeof RemolquesRoute
  '/reportes': typeof ReportesRoute
  '/tractos': typeof TractosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dho': typeof DhoRoute
  '/productividad': typeof ProductividadRoute
  '/remolques': typeof RemolquesRoute
  '/reportes': typeof ReportesRoute
  '/tractos': typeof TractosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dho': typeof DhoRoute
  '/productividad': typeof ProductividadRoute
  '/remolques': typeof RemolquesRoute
  '/reportes': typeof ReportesRoute
  '/tractos': typeof TractosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracion'
    | '/dho'
    | '/productividad'
    | '/remolques'
    | '/reportes'
    | '/tractos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracion'
    | '/dho'
    | '/productividad'
    | '/remolques'
    | '/reportes'
    | '/tractos'
  id:
    | '__root__'
    | '/'
    | '/configuracion'
    | '/dho'
    | '/productividad'
    | '/remolques'
    | '/reportes'
    | '/tractos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  DhoRoute: typeof DhoRoute
  ProductividadRoute: typeof ProductividadRoute
  RemolquesRoute: typeof RemolquesRoute
  ReportesRoute: typeof ReportesRoute
  TractosRoute: typeof TractosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tractos': {
      id: '/tractos'
      path: '/tractos'
      fullPath: '/tractos'
      preLoaderRoute: typeof TractosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remolques': {
      id: '/remolques'
      path: '/remolques'
      fullPath: '/remolques'
      preLoaderRoute: typeof RemolquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productividad': {
      id: '/productividad'
      path: '/productividad'
      fullPath: '/productividad'
      preLoaderRoute: typeof ProductividadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dho': {
      id: '/dho'
      path: '/dho'
      fullPath: '/dho'
      preLoaderRoute: typeof DhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  DhoRoute: DhoRoute,
  ProductividadRoute: ProductividadRoute,
  RemolquesRoute: RemolquesRoute,
  ReportesRoute: ReportesRoute,
  TractosRoute: TractosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
